from __future__ import annotations

USB_APP_TO_RADIO_PREFIX = 0x3C  # ASCII '<'
USB_RADIO_TO_APP_PREFIX = 0x3E  # ASCII '>'

DEFAULT_MAX_FRAME_PAYLOAD = 1024
MAX_CHANNEL_TEXT_BYTES = 133

CMD_APP_START = 0x01
CMD_SEND_CHANNEL_MESSAGE = 0x03
CMD_SYNC_NEXT_MESSAGE = 0x0A
CMD_GET_BATTERY = 0x14
CMD_DEVICE_QUERY = 0x16
CMD_GET_CHANNEL = 0x1F

PACKET_OK = 0x00
PACKET_ERROR = 0x01
PACKET_SELF_INFO = 0x05
PACKET_MSG_SENT = 0x06
PACKET_CONTACT_MSG_RECV = 0x07
PACKET_CHANNEL_MSG_RECV = 0x08
PACKET_NO_MORE_MSGS = 0x0A
PACKET_BATTERY = 0x0C
PACKET_DEVICE_INFO = 0x0D
PACKET_CONTACT_MSG_RECV_V3 = 0x10
PACKET_CHANNEL_MSG_RECV_V3 = 0x11
PACKET_CHANNEL_INFO = 0x12
PACKET_CHANNEL_DATA_RECV = 0x1B
PACKET_MESSAGES_WAITING = 0x83

SUPPORTED_CHANNEL_MESSAGE_PACKETS = {
    PACKET_CHANNEL_MSG_RECV,
    PACKET_CHANNEL_MSG_RECV_V3,
}

