[build-system]
requires = ["setuptools>=69"]
build-backend = "setuptools.build_meta"

[project]
name = "meshcore-control-bridge"
version = "0.1.3"
description = "Home Assistant App for MeshCore Control Bridge"
readme = "README.md"
requires-python = ">=3.12"
license = { text = "Apache-2.0" }
authors = [
  { name = "Jeudiel Guerrero" },
]
dependencies = [
  "httpx>=0.27",
  "PyYAML>=6.0",
  "websockets>=12.0",
]

[project.scripts]
meshcore-control-bridge = "meshcore_control.main:main"

[tool.setuptools.packages.find]
where = ["src"]
